global:
  scrape_interval:      5s
  evaluation_interval:  5s


scrape_configs:
  - job_name: 'BaselineFuzzer'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'MutationDeltaFuzzer'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'PatternMatchingFuzzer'
    static_configs:
      - targets: ['host.docker.internal:8083']
