passes:
  - min_length: 32
    max_length: 64
    mode: min_token_count
    token_count: 50
    threshold: 0.0
  - min_length: 16
    max_length: 64
    mode: threshold
    threshold: 0.4
    token_count: 0
  - min_length: 4
    max_length: 64
    mode: threshold
    threshold: 0.3
    token_count: 0

min_corpus_size: 250
search_interval: 2000
max_tokens: 2500
recent_entries_count: 2500
clean_tokens: false