extractor:
  type: corpus

pipeline: []

min_corpus_size: 500
search_interval: 2000
max_tokens: 10000
max_token_length: 64
min_token_length: 3
search_pool_size: 2500
displayed_tokens: 30

fuzzer_preset: baseline # no token discovery
scheduler_preset: fast
timeout_secs: 8
silent_run: true

cores: "10-14"
broker_port: 1339
prometheus_host: "0.0.0.0"
prometheus_port: 8081
corpus_dir: "./corpus"
crashes_dir: "./crashes_base"